### ISSUE TITLE
Bug when i compile your plugin with maven

### ISSUE THREAD

**Issue by Khran** [elsiff/MoreFish#1]
Hello, I'm french!
I need change more text in your code for my personal usage but when i compile with maven, i get a strange bug. The "§6text" get changed to Âtext (color gold) in minecraft. It's the first time in get this lol.

Thx for your help !

**Comment by ZeegCL** [comment]
This is an encoding issue due to the "§" symbol

**Comment by Khran** [comment]
Sorry, i miss to close this ticket, i solved my problem xD
