### ISSUE TITLE
Double position after re-log

### ISSUE THREAD

**Issue by TheoMarque** [elsiff/MoreFish#3]
In some situation, when player re-log during fishing contest has two stats and finally - two places. Example in screenshot. 

In screenshot - Player Redex2 re-logged and counted twice. But reward is only one, from highest position.
![2017-01-15_19 57 04](https://cloud.githubusercontent.com/assets/19385639/21966971/03eadd10-db7e-11e6-908e-4da64a4c3ebc.png)

**Comment by woodyn1002** [comment]
Thanks for reporting. Could you send me your config and fish files? It'll
be very helpful.

2017-01-16 7:56 GMT+09:00 TheoMarque <notifications@github.com>:

**Comment by TheoMarque** [comment]
[MoreFish.zip](https://github.com/elsiff/MoreFish/files/709558/MoreFish.zip)
