### ISSUE TITLE
Could not pass event PlayerFishEvent to MoreFish v2.1.2

### ISSUE THREAD

**Issue by C4BR3R4** [elsiff/MoreFish#6]
Error in console https://hastebin.com/kimopexuni.vbs

**Comment by woodyn1002** [comment]
Could you show me more details: MC version, yml files, plugins list...

**Comment by C4BR3R4** [comment]
Version MC: Spigot 1.11.2-R0.1 #1251

Config.yml https://pastebin.com/7CZLAtbE
fish_es.yml https://pastebin.com/vFtjgdfP
lang_es.yml https://pastebin.com/ELsq71WD

Plugins: neoPaintingSwitch, PlugMan, VariableTime, BestAdminChat, FlyingCarpet, SketchMap, CreativeNbtControl, ijmh, ProtocolLib, Multiverse-Core, DeathMessagesPrime, VotingPlugin, MVdWPlaceholderAPI, FastAsyncWorldEdit, PermissionsEx, FeatherBoard, mcMMO, BetterElytra, Multiverse-Portals, PlaceholderAPI, VipZeroFIX, CameraObscura, SmokingPipes, FastCraftPlus, Thirst, EditableSign, CustomDeathDrops, JailWorker, InfoBook, CoreProtect, dynmap, WorldEdit, FrameProtect, OpenInv, AnimatedNames, AnimalPlague, SkQuery, WorldBorder, Gringotts, Votifier, LibsDisguises, JChairs, CS-CoreLib, Vault, TheTime, Parties, KillerMoney, LWC, Skript, MarriageMaster, Jobs, mcMMOAction, MessageAnnouncer, Citizens, Sentinel, CustomGUI, CrazyAuctions, Herochat, DabCore, VipZero, WorldGuard, Slimefun, MoreFish, RemoteController, SignBoard, SimpleAlias, Umbaska, BossShop, Denizen, Essentials, MCBans, LWC-Economy, BookShelf, HeadDatabase, Dynmap-WorldGuard, BannerMaker, AdvancedAchievements, ExoticGarden, SuperVanish, GriefPrevention, UltimateArena, Depenizen, ServerSigns, Statz, Bank, TitleManager, Reputation, EssentialsChat, ItemFrameShops, JDynmapGriefPrevention, MCJukebox, Brewery, EssentialsAntiBuild, EssentialsSpawn, MyPet, SoundControl, Autorank, ProtectionLib, FurnitureLib, FurnitureMaker, DiceFurniture
